### ISSUE TITLE
Thoughts on pooling/sharing actions?

### ISSUE THREAD

**Issue by jswigart** [luxkun/ReGoap#3]
I am tinkering with using ReGoap in situations where there is a plurality of actions that may satisfy a goal, which is different from the simplistic approach that the included example used(singleton resource managers, etc). The reason being is that I want to try and use the planner to create a good solution using some spatial considerations as well, which is not something the example does. Naturally this can create quite a number of action instances. Have you considered or thought about setting the actions up in a more dynamic or poolable manner, where the actions can be considered more globally available for any number of agents, rather than each agent having copies of them?

To get an idea what I'm shooting for, consider if the GoapTest example that is included allocated an action per instance of a tree resource, bank resource, workstation resource, etc, with conditions based on it's spatial location. The idea here is that provided the GoTo actions estimated their cost based on distance or travel time, the overall plan should represent the most efficient set of actions to perform based on travel time as well as just fixed action costs.

Seems GOAP isn't used that often in this manner, but I wanted to get your thoughts on the feasibility of globalizing a set of the actions rather than having to clone potentially dozens per agent.

Alternately, if you have a reasonable way to configure the conditions through the planner that might avoid the need to have an action per in-world resource and still get reasonable spatial considerations, I'm interested in that too.

Thanks

**Comment by luxkun** [comment]
Could you explain why would you want to share Actions between many agents?
I don't see any advantages except, maybe, performance.

Talking about a way to configure actions to have spatial considerations you can just override GoapAction.GetCost and calculate the GoTo's cost yourself (if possible calculate it in GoapAction.Precalculations!).
Of course to do this you would still need to create an action for every different GoTo type, like done in the example.

What you are asking is how to implement generic actions? (ex. a generic GoTo for every movement without having to implement different classes for every movement like in the FSMExample?)

**Comment by jswigart** [comment]
Thanks for the speedy reply.

If you imagine an RTS game in the realm of the example, you may have dozens of gathering units and hundreds or thousands of resource nodes, many workstations, "banks", etc. Cloning all those actions within each individual agent doesn't seem like an ideal use of memory or cpu. Plus, depending on how you implemented the world action pool, those actions could be attached to the very objects that can satisfy those actions, much like a sims-like smart object, so that its lifetime management is much easier than adding/removing components from each individual agent.

I also have a desire to not have individual goto types(based on destination type at least). That doesn't seem like the way to do it, from my reading of the fear papers and such. I see the goto action as a type of movement, a walking action, a flying action, that change the behavior of the action of moving itself, and that use generic conditions like locality to a destination to drive their selection. I gather that making goto variations based on destination types make the configuration of the conditions a bit easier, but I can't help but feel that it is not the right direction. If you imagine a game with 5 creature locomotion types, and 5 resource types, you start seeing an explosion of move action types if you built your move actions with a particular destination type in mind. 

A move action gets you in proximity to some position, I don't see why it should be any concern of the move action itself whether it is moving to a resource or bank or whatever. I would imagine that during the planning phase, the current position and the destination position world state variables would be changing throughout each step of the plan, and the move actions would only need to estimate travel times based on those planner variables. Can you explain why you chose to have destination typed goto actions? Maybe I am missing an important reason here.

Thanks

**Comment by luxkun** [comment]
I got it now, I think as well that the way to go is having a generic goto action like Jeff Orkin's Fear.

I have uploaded a new branch that handles wildcard effects/preconditions and, by simply adding a next GoapAction as parameter in some IReGoapAction's methods, that can be archieved now (and of course the planner is handling this).
Check it out, let me know if these changes fulfil the requirements you asked about GoTo:
https://github.com/luxkun/ReGoap/tree/dynamic-effects-and-preconditions
**Note**: this is not fine tested and breaks the current API, that's why I have created a secondary branch

This is a generic feature, it can be used for GoTo or for anything else (like "ActivateSmartObject"?), so that should also fulfil the requirement of having generic actions for generic resources and such.

So my idea is that you can create an agent with a single "CollectResource" action that finds the closest/needed resource/smartobject (ideally in "Precalculations"), with a precondition (dynamically changed every call of "Precalculations" or "GetPreconditions")

Important: this feature is available ONLY in Backward search (I think forward search has to go even more now)

Let me know if this is what you required and if it works like you want.

**Comment by jswigart** [comment]
Thanks! I will try tinker with it soon as I can and provide feedback.

**Comment by jswigart** [comment]
I appreciate that wildcard change. That will help keep actions generic.

I'm not quite seeing how this resolves the smart object issue, specifically the "many actions of type" issue that was described earlier. The resources in the game still appear to be effectively narrowed to singular actions by the selection of "nearest tree" in the tree sensor for instance. Not to say that is not a valid way to do things, because that is certainly a way to keep things cheap in a complex environment, by narrowing the context of certain classes of actions separately from the planning phase. It's just that for uses that want the plan to account for travel time properly, they would need to have a way to treat each resource independently.

Here's what I would propose. If you aren't interested in this for the core library, that is fine too, I can fork and do this part on my own, though it would be less ideal in keeping up with any other changes.

I think I would do something like this.

- Allow actions to be marked "global". There can be a checkbox on the GoapAction base class, or if warranted, maybe subclass GoapAction as GlobalGoapAction if there is good reason to create a harder dividing line.
- If an action is a global action it registers with GoapPlannerManager.instance.RegisterGlobalAction(), and de-registers on destroy
- Extend the planner to consider and expand its search on global actions as well as the actions that are on an agent.

Seems simple enough, though there would need to be some minor refactoring to eliminate the agent member variable from the actions. Obviously GoapActions would need to be fully divorced from ownership with a particular agent, and have the agent just passed in to the interface functions instead(to Run, etc). That also means than any state that needs to be tracked by the actions could not be stored as member variables for those global, but that can be worked around pretty easily, via a blackboard on the agent or storing things in its shared memory. I would think that most "world" actions would not tend to be very stateful things(at least with agent specific information)

With these relatively simple changes, not only could you facilitate more complex spatially aware plans, but you could eliminate a ton of component instances that would otherwise have to be managed on each agent.

In the context of the ExampleFSMScene, there could be a global action on each resource for example, which would obviously increase the planning cost, but when the plan considers each one, travel time estimates can assist the plan in selecting the most efficient one. 

There are many contexts where this type of goap use would be absolutely required if one wanted to achieve certain behaviors.

- Going to the nearest resource to the agents current position is not necessarily the most efficient plan, for a variety of reasons, such as maybe it moves you away from the delivery point, so the combined overall travel time would be worse, etc
- If your resource gatherer could hold multiple resource types, the plan would favor getting all he could by visiting the least number of resource nodes, likely passing up nearby resource nodes with only a few for the ones he can load up on more units of the resource in one go.
- If your resource gatherer moved at different speeds based on how loaded down he was. Resource selection would be even more important. Minimizing the loaded down time would be, and the plan would solve that by gathering resources nearest to where they need to take them, simply by having the travel time estimates apply a loaded multiplier to the travel time.

Providing support for such global actions is not mandating people use it in this way of course. For many different uses it's a perfectly sane choice to narrow the planner search space like the example does now, but to some types of behavior like the above, it is really the only way to get there.

Thoughts?

**Comment by jswigart** [comment]
Related to this, I think a global goal pool would be very useful as well. In an RTS game, a GoalConstructBuilding might be instantiated as a component of the building, and any agents that can contribute to building can see that single global goal as if it were their own. As a single instance, it becomes much easier and cheaper to dynamically adjust the requirements of the plan as resources are delivered and/or work is done, rather than doing that work for every agent in the scenes copy of that goal.

**Comment by luxkun** [comment]
I think this can be already done with a component (something like GlobalActionPooler), which automatically adds nearby (or all) actions from a pool (GlobalActionPool) to the current agent.
Am I wrong? Of course this would have the "problem" to have multiple actions for every agent.
Another approch is to have an action that automatically gets SmartObjects (an object which has all the informations the action need to operate) in someway (nearby, facing, your logic here) and changes its preconditions and effects based on the smartobject, the goal could also do the same like you proposed.

As for the resources the current example can be made more generic having a single action to gather any resource, this is not very complicated at all, just remove resourceName and dynamically update it with your logic.

But I get why you want to do this, it's simplier and has less overhead since you don't have to instantiate the actions for every agent, but I'm pretty sure this is almost negligible (if this is not the case an example with performance profiling would be nice).

It's the same with goals of course.

I'm open to add this to the library, but working on other things right now, also I'm unsure if I would ever use this or the normal approach, since this does not add anything to the things the agent can do, so if you're interested in implementing this I would appreciate a pull request with your changes, pull requests are always welcome! 👍

**Comment by jswigart** [comment]
I think my chief concern is with the cost ramping up(with each agent) of doing whatever analysis of the environment is required to generate certain actions. That part could still be globalized and submitted to a pool, and then the agents would need to dynamically at runtime sort of mirror that global pool in the form of instantiating child actions based on that pool, and do all the runtime bookkeeping required to keep them in sync.

I'm fine with implementing something myself and doing a PR, I'm just a bit on the fence still about the approach. At first glance it doesn't seem very detrimental to make actions stateless with respect to a particular agent(remove the agent ref, etc), in favor of passing it in to the various functions, but that's the kind of thing that can easily come back to bite you. It may be safer, if more costly, not to break the current action paradigm.

I'm thinking there might be a hybrid approach, where there is a single GatherResource action on the agent, but which gets expanded upon during the search inside a loop based on a globally instantiated resource action pool. That eliminates the per agent book keeping and memory bloat, and keeps the action itself on the agent, so it could still hold state.

Something like
ActionGatherResource - associated with a type ActionResourceInstance

Then at the planner level
if(action has associated instance type), expand search for each instance of that action in the global pool

**Comment by jswigart** [comment]
I've forked the repo to experiment with some of these topics. I got a shared action pool working last night. Haven't pushed yet but I will when I get it a little further.

**Comment by jswigart** [comment]
Related to this, I don't have the code in front of me but do you recall the reasoning for doing the default(Vector3) preconditions and such? I think there was a todo comment about finding a workaround. Is that because there isn't a convention of clearing state for an effect?

**Comment by luxkun** [comment]
Are you talking about the SetDefaultEffects method? here:
https://github.com/luxkun/ReGoap/blob/master/Unity/FSMExample/Actions/GenericGoToAction.cs

It's not strictly needed to have preconditions and effects with a value even when the action hasn't processed them (talking about dynamic actions), but it looks clearer to have them, to me.
One thing that could change is using a Vector3? intead of a plain Vector3, but it has an additional overhead which isn't really needed.

**Comment by jswigart** [comment]
Yea. I understand you have to seed "isAtPosition" with something or the planner won't know that it can use that action to satisfy that condition.

I'm talking about the todo: in 
https://github.com/luxkun/ReGoap/blob/98b01c8ac62bfb0207b14a885a03477add7b221a/Unity/FSMExample/Actions/CraftRecipeAction.cs

Was there some issue that required that action to have an "isAtPosition" effect of zero?

**Comment by luxkun** [comment]
Basically with the current approach the planner wouldn't understand that the "isAtPosition" hasn't yet been setted yet, in the real world plan, while trying to check missing preconditions.

What happened with CreaftRecipeAction (without resetting isAtPosition in the effects) is that the planner would put right after the 1st CraftRecipeAction the GoTo action and think that the 2nd CraftRecipeAction (which was after the GoTo, so before in real world) preconditions were fine.
By resetting the isAtPosition I was forcing the planner to add a new GoTo action right after any CraftRecipeAction.

I have changed the core of ReGoapNode, where the new goal is calculated, this is quite big for old codes, also I have dropped the false preconditions support (the planner basically was ignoring false preconditions with the predicate in MissingState, removed this since it's the same but force the library's users to remove any false precondition).

Now the whole action precondition is added to goal and then the goal is cleared with the world's state and the current action effects.

The tests are all fine and so is the fsmexample, let me know if you have any problem with the new changes.

Commit: https://github.com/luxkun/ReGoap/commit/bf7526c69d836caf9c1e06727830bf0325f9190e
