### ISSUE TITLE
Improve Action Cost calculation

### ISSUE THREAD

**Issue by jswigart** [luxkun/ReGoap#7]
Currently the "next" action doesn't appear to be getting passed to the GetCost function.

Related to this, I'm trying to think through the requirements for having the information necessary to accurately estimate travel times into the cost of an action. Essentially the action needs to know the start and end positions that the actions is attempting to cover for cost purposes.

Correct me if I'm wrong, but given that it is a backwards search, I *think* the goalState passed into GetCost will have the destination, including any intra-plan moves in the form of isAtPosition/isAtTransform conditions, so the move action should be able to pull out those values with GetObjective as the examples do.

As for the "start", given that it is a backwards search, that will always be the agent current position correct? (alternately a forward search would have to pass positional estimates through the world state each step of the plan I think)

**Comment by jswigart** [comment]
May I also suggest that the cost fields be turned into floats to better facilitate accuracy of things like travel times or costs that are less than 1 unit?

**Comment by luxkun** [comment]
GetCost is called with next actions now:
https://github.com/luxkun/ReGoap/commit/8f9360868f5d1f8f4844ca3995e605a41f947de9

As for the cost's type it used to be a float but then I changed it to int for performance, but afterall it shouldn't matter at all right now, so I'm going to change it to float.

> Essentially the action needs to know the start and end positions that the actions is attempting to cover for cost purposes.
So we got the end, its the objective, as for the start you need the current state (we have this since the ReGoapNode updates its state every time the A* expands the current node), but it's not currently a parameter in GetCost, so it needs to be changed.

I'll check out if there are no other way, if so I'll add it.

**Comment by luxkun** [comment]
Actions's costs and goal's priorities are now float:
https://github.com/luxkun/ReGoap/commit/419a602bb76691a4efee38276cf8c2cbead5736a

**Comment by luxkun** [comment]
> As for the "start", given that it is a backwards search, that will always be the agent current position correct? (alternately a forward search would have to pass positional estimates through the world state each step of the plan I think)
No because agent's current position (as in transform.position) is not updated by the planner, which simulates actions effects without doing anything at all in the real world state.
Also it's advised to not use any Unity component in the actions thread-safe methods, or else you won't be able to use multi-thread in the planner manager.

**Comment by luxkun** [comment]
So thinking more thoroughly about this I have no idea how to do it, let me explain with an example:
1) the planner gets the goal which is *killEnemy: true* and *closeHealFriend: true*
2) finds the first action that fulfil part of the goal which is "KillEnemy", which has precondition *isAtPosition: enemyVector3*
3) the new goal is *isAtPosition: enemyVector3* and *closeHealFriend: true*, so the planner finds the action GoTo which has a dynamic effect *isAtPosition: enemyVector3*, but we have no idea, at this point, where the agent will be, since there could be another action that changes the agent position
4) next: HealCloseFriend (effect: *closeHealFriend: true*) but has a precondition of *isAtPosition: friendVector3*
5) next: GoTo with dynamic *isAtPosition: friendVector3*, now we could use the current agent position (could do this since the goal is empty), but doesn't seem like a good way to fix this and anyway the other GoTo actions won't be able to find the current action position.

So any idea how to resolve this? not going back to forward which won't be able to get the wanted goal position anyway.

**Comment by jswigart** [comment]
Yes you are right. I think the world state needs to track a variable(or use isAtPosition, isAtTransform) to track a dynamic position through the plan, so isAt* needs to be seeded at plan start so that it can be used in action cost estimations. Think we have that information by looking up isAt in the goal state passed into GetCost right? (and comparing it to the positional requirements of the 'this' action) ?

**Comment by luxkun** [comment]
So you are saying to save isAtPosition at planning start to current position? but that will give only first (real, as in last in backward search) GoTo action the real position, the others won't have the updated one.

KillEnemy -> GoTo (planning still didn't choose "CloseHealPlayer" so we have no idea what will be next position in backward search, so previous position in real world, also current goalstate will have isAtPosition that's killenemy's isAtPosition, current version of GoTo uses this) -> CloseHealPlayer -> GoTo (can use isAtPosition "saved" from the plan, but could anyway use goapmemory)

**Comment by jswigart** [comment]
During the planning, there is a ReGoapState cloned and updated with the effects of each action right? Doesn't that mean that in any particular action, the action may have an "isAt*" state that represents whatever sequence of actions came before it? If my parent chain of actions had 100 move actions into it, wouldn't the ReGoapState passed to me contain the last?

**Comment by luxkun** [comment]
But before is *after* in the real world.

The planner does not know what's coming after the current action, so if the planner choose KillEnemy as first action (last in real world) and is now asking GoTo's cost there is no way to know yet that the next 
action picked by the Goap is going to be CloseHealPlayer.

**Comment by jswigart** [comment]
If a plan for an open door goal was
moveto_key1
pickup_key1 (req isAt "key1")
moveto_door
unlockdoor(req isAt "door", has "key1")

Just to think through the planner flow(hopefully accurately)
1) only moveto_door action initially satisfies any conditions, there are no "isAt" states set in the search state yet, so the cost estimate would use the isAt seeded at plan start, which is the current position, so the cost estimate would be agent position to door
2) has key1 still not satisfied, so  pickup_key1 action is pushed. It has positional requirements which require a re-costing of the parent(in this case moveto_door). *
3) moveto_key1 pushed to satisfy moveto key1

The guess the issue here is that any time an action is pushed onto the search, or more specifically, an action with spatial requirements, that action should probably calculate it's cost by re-asking any action before it(or after in real world ordering), for an updated cost calculated with respect to this new action.

Like when pickup_key1 is pushed and goes to calculate its cost. It needs to calculate with respect to the requirements of pickup_key1, which means letting moveto_door recalculate its cost based on the positional requirement. It's trickier than that bc it may require looking up through many parent actions to recalculate costs. There's no guarantee that the move action is the direct parent. Spatial requirements have such special considerations in these ways that I think it is worth considering that they are special types of conditions. I don't have a clear thought about how to do that though.

Maybe anything with spatial requirements or effects need to do a more substantial enumeration of one or more of the search parent chain in order to function properly.

**Comment by jswigart** [comment]
I think that GetCost needs to be passed in the ReGoapState for the node instead/in addition to the "next" action by itself, because the next action may not be an action that provides a spatial effect. There could be one or more intermediate actions in between an action that moves you somewhere, and the next action that moves you somewhere else. If the node state were passed in, it should provide access to the last "isAt*" effect no matter how far removed from the current node it was last set(by the cumulative effect of  state += effects)

I suppose for recalculating the cost I might move parent.GetPathCost down to after the state += effects as well, and pass in the goap state. Most actions won't care about the parameter, but a move action will need it to calculate a cost for any node that precedes it.

**Comment by luxkun** [comment]
Tbh I don't see how to do this, since the action goto X doesn't know if there is another goto Y in the plan.

If you know how to do this please do a fork and show me what's your idea.

**Comment by jswigart** [comment]
It wouldn't know that directly. It should be able to on account of the contents of the goap state passed in. At least that is the thinking. I'll try and whip something up soonish as a proof of concept.
